env:
  browser: true
  es2021: true
extends:
  - standard
parserOptions:
  ecmaVersion: 12
  parser: '@typescript-eslint/parser'
  sourceType: module
plugins:
  - '@typescript-eslint'
rules: {
  'no-console': 'error',
}
