env:
  browser: true
  es2021: true
extends:
  - 'plugin:vue/essential'
  - standard
parserOptions:
  ecmaVersion: 12
  parser: '@typescript-eslint/parser'
  sourceType: module
plugins:
  - vue
  - '@typescript-eslint'
rules: {
  'no-console': 'error',
  'vue/no-multiple-template-root': 0
}
