env:
  browser: true
  es2021: true
extends:
  - standard
  - plugin:@typescript-eslint/eslint-recommended
  - plugin:@typescript-eslint/recommended
parserOptions:
  ecmaVersion: 12
  parser: '@typescript-eslint/parser'
  sourceType: module
  project: "tsconfig.json"
plugins:
  - '@typescript-eslint'
rules: {
  'no-console': 'error',
}
root: true